### ISSUE TITLE
Address security vulnerability

### ISSUE THREAD

**Issue by jaebradley** [GrooveLabs/action-utils#2]
![image](https://user-images.githubusercontent.com/8136030/57038723-74b77480-6c0f-11e9-8c18-4465ce0e3d7e.png)

![image](https://user-images.githubusercontent.com/8136030/57038752-89940800-6c0f-11e9-8cab-abaf7fe3ffef.png)

This should block the installation of this package anywhere in Groove.

**Comment by marndt** [comment]
Pretty sure this was fixed in https://github.com/GrooveLabs/action-utils/commit/f8939001bd77e80cefd48bb3205f067dccae91a9#diff-32607347f8126e6534ebc7ebaec4853d

**Comment by jaebradley** [comment]
![image](https://user-images.githubusercontent.com/8136030/57038979-2f477700-6c10-11e9-8006-caf0b0fcb833.png)

@marndt I just pulled `master`, installed and `audit`ed and I see this.

**Comment by marndt** [comment]
oic

**Comment by jaebradley** [comment]
Open issue with `semantic-release`: https://github.com/semantic-release/semantic-release/issues/1147

**Comment by vijaypemmaraju** [comment]
`groove-wysiwyg-editor` has the same ones too: 

![image](https://user-images.githubusercontent.com/1395086/57039326-358a2300-6c11-11e9-9074-c13ca8226657.png)

**Comment by vijaypemmaraju** [comment]
Also, FWIW, this is only a dev dependency, so it shouldn't actually be used anywhere where the package is installed

**Comment by vijaypemmaraju** [comment]
fixed a while back
